Css basics
Laboratoria/admission-curriculum pull request #60
Opened 2021-04-15 21:34 UTC by moniyama

2021-04-20 22:03 UTC, merunga requested changes

2021-04-20 22:03 UTC, merunga commented on admission/03-prework/05-css-basics/sandboxes/03-sizing/README.md
> +centímetros, pulgadas o pixeles.
```suggestion
centímetros (`cm`), pulgadas (`in` del inglés _inches_) o pixeles (`px`).
```

@moniyama creo q estaría bueno ademas linkearles este recurso https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#lengths

2021-04-20 22:03 UTC, merunga commented on admission/03-prework/05-css-basics/sandboxes/03-sizing/README.md
> +- [Unidades y medidas - Librosweb](https://uniwebsidad.com/libros/css/capitulo-3/unidades-de-medida?from=librosweb)
usaría los de MDN q he puesto arriba

2021-04-20 22:03 UTC, merunga commented on admission/03-prework/05-css-basics/sandboxes/03-sizing/README.md
> +- [Colores - Librosweb](https://uniwebsidad.com/libros/css/capitulo-3/colores?from=librosweb)
usaría los de MDN q he puesto arriba

2021-04-24 00:03 UTC, moniyama commented on admission/03-prework/05-css-basics/sandboxes/03-sizing/README.md
> +
Add la image con una frase.. No sé se necesita más explicaciónhttps://github.com/Laboratoria/admission-curriculum/pull/60/commits/33542ebe2c1605ddeb4d0b50275caaa2c492b368

2021-04-24 00:07 UTC, moniyama commented on admission/03-prework/05-css-basics/sandboxes/03-sizing/README.md
> +- [Unidades y medidas - Librosweb](https://uniwebsidad.com/libros/css/capitulo-3/unidades-de-medida?from=librosweb)
Saqué los links de librosweb e coloqué los otros dos que fue dicho arriba.. https://github.com/Laboratoria/admission-curriculum/pull/60/commits/7fbdc47c453c0b1910affa9266e9bf1128f56d54

2021-04-24 00:09 UTC, moniyama commented on admission/03-prework/05-css-basics/sandboxes/03-sizing/README.md
> +centímetros, pulgadas o pixeles.
crees q tiene que poner algunas explicaciones o solo en los links en lectura complementarias es bastante?

2021-04-24 00:10 UTC, moniyama commented on admission/03-prework/05-css-basics/sandboxes/01-intro/README.md
> +{% endspoiler %}
https://github.com/Laboratoria/admission-curriculum/pull/60/commits/e6119cd3b05d34427a204df126117b645c99aade

2021-04-28 19:39 UTC, merunga commented on admission/03-prework/05-css-basics/sandboxes/03-sizing/README.md
> +- [Percentage - MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/percentage)
```suggestion
- [Porcentaje - MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/percentage)
```

2021-04-28 19:40 UTC, merged