Test js dom
Laboratoria/admission-curriculum pull request #92
Opened 2021-05-17 21:03 UTC by moniyama

2021-05-18 19:28 UTC, moniyama commented
@merunga

2021-05-19 13:36 UTC, merunga requested changes
buenisimos los tests @moniyama !

2021-05-19 13:36 UTC, merunga commented on admission/03-prework/06-js-basics/solution/08-dom-api-basics/test/index.spec.js
> +const variablesDeclared = utils.getAll(ast, 'VariableDeclaration').map(
Esta variable solo se utiliza una vez. Deberia definirse en el scope local del test q la necesita

2021-05-19 13:36 UTC, merunga commented on admission/03-prework/06-js-basics/solution/08-dom-api-basics/test/index.spec.js
> +      .filter(item => item.event === "click")
@moniyama aqui deberias extender a otros eventos validos para el elemento en cuestion:
```js
const element = document.createElement('input'); // esta deberia ser la referencia al elemento real

// primero buscamos todas las propiedades del elemento
const elemProps = Object.getOwnPropertyNames(Object.getPrototypeOf(Object.getPrototypeOf(element)));

// y filtramos las que no son "onX"
const eventNames = elemProps.filter(k => k.startsWith("on") && (element[k] === null || typeof element[k] === "function")).map(k => k.slice(2));
```

2021-05-26 18:13 UTC, merunga approved these changes

2021-05-26 18:13 UTC, merunga commented on admission/03-prework/06-js-basics/sandbox/08-dom-api-basics/test/index.spec.js
> +    const element = document.createElement('input');
esto creo q no quedo claro

2021-05-26 18:14 UTC, merged